# Generated by Django 4.2.12 on 2024-07-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='state',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
    ]
