# Generated by Django 4.2.12 on 2024-07-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_menu_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
