# Generated by Django 4.2.12 on 2024-07-06 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_expiration_date_alter_product_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 17, 28, 37, 991969, tzinfo=datetime.timezone.utc), verbose_name='Caducidad'),
        ),
    ]
