# Generated by Django 4.2.12 on 2024-07-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='state',
            field=models.CharField(choices=[('N', 'Normal'), ('A', 'Anulada'), ('M', 'Modificada')], default='N', max_length=1, verbose_name='Estado'),
        ),
    ]
